### ISSUE TITLE
About functions and variables

### ISSUE THREAD

**Issue by MasterJH5574** [peterzheng98/Compiler-2020#21]
Are the two behaviors below valid?
* Use a variable before its declaration.
* Call a function before its definition.

For example, consider the following code. Are these two behaviors valid?
```java
int main() {
    a = 0; // Use variable "a" before its declaration.
    int a;
    func(); // Call function "func" before its definition.
}

void func() {
    println("Hello world!");
}
```

**Comment by MasterJH5574** [comment]
And another question:
Do the parameter part and the body part of a function belong to the same scope?

**Comment by peterzheng98** [comment]
For question 1: More information is in Chapter 13.
Use a variable before its declaration. : **Invalid** - Chapter 13(4)
Call a function before its definition. : **Valid** - Chapter 13(5)

So in the given example, `a=0` is invalid while calling `func()` is valid.

**Comment by peterzheng98** [comment]
For question 2: **Very Good question**
The parameter part and the body part of a function share the same scope.
If you find some test cases that doesn't satisfy this rule, feel free to have a new issue about it.
