### ISSUE TITLE
About conditional/loop expressions

### ISSUE THREAD

**Issue by oscardhc** [peterzheng98/Compiler-2020#22]
According to section 11, the expression `if (1 == 1) foo(bar);` is invalid but this kind of expression was used in section 13.
Do code blocks in conditional expressions necessarily contains `{ <code> }` ?

**Comment by peterzheng98** [comment]
`if(1==1) foo(bar);` should be considered **VALID**.
`{}` is not required if there only exists one.
More discussion is **welcomed**.
