### ISSUE TITLE
About loop expressions

### ISSUE THREAD

**Issue by Yveh** [peterzheng98/Compiler-2020#23]
> for (init; condition; incr) {
	\<Expressions and Statements if true\>
}
Can `init` and `incr` be code blocks?

**Comment by MasterJH5574** [comment]
I think `init`, `cond` and `incr` are all expressions?

**Comment by peterzheng98** [comment]
init, cond, incr should be expression.
Correct: for(i = 0; i < 10; ++i)
Claim: In order to simplify, init cannot be declarations.
**Incorrect**: for(**int i = 0**; i < 10; ++i)

**Comment by wu-qing-157** [comment]
It seems that the incorrectness of init being declarations is mentioned neither in language document, nor in sema test cases.
