### ISSUE TITLE
Question about data set : basic-66

### ISSUE THREAD

**Issue by fstqwq** [peterzheng98/Compiler-2020#25]
```cpp
    foo.foo.foo.(foo).foo.foo.foo.g().foo.b = getString().length();
```
I can't understand the `.(foo)` usage of `.`. 
In doc 8.3 it should be `<ClassObjectIdentifier>.<Identifier>`, I think there's no bracket allowed.

Addtionally, I found following code CE using different versions of g++ with message `expected unqualified-id before ‘(’ token`
```cpp
class test {
	public:
	int a;
};
int main() {
	test a;
	a.(a) = 1;
}
```
Following code CE using Java 8 with message `error: need<Identifier>`
```cpp
public class test {
	public String a;
	public static void main(String[] args) {
		test A = new test();
		A.(a);
	}
}
```

**Comment by peterzheng98** [comment]
Very good suggestions.
It has been fixed.
