### ISSUE TITLE
Is there a must to have a semicolon after class declaration?

### ISSUE THREAD

**Issue by fstqwq** [peterzheng98/Compiler-2020#26]
According to 8., class declaration should have a semicolon after it.

But in several test data (i.e. basic-48), there's no semicolon after it. Surprisingly all those data fail with other reasons but not the semicolon.

So is there a must to have a semicolon after class declaration (like C++)? Or like Java the semicolons are parsed as empty statement.

**Comment by peterzheng98** [comment]
Semicolon is required for class definition.
The comment is **NOT** the only reason that the data fails. Actually, we will not judge whether you have identified the type of errors.
