### ISSUE TITLE
How to dynamically allocate memory and IO in RISC-V simulator?

### ISSUE THREAD

**Issue by cla7aye15I4nd** [peterzheng98/Compiler-2020#27]
If use a simulator to run RISCV code, how to implement input, output and dynamically allocate memory ? These operations seem to depend on the operating system.

**Comment by Engineev** [comment]
@cla7aye15I4nd Hello, I am the one who is implementing the simulator. You can assume that some common C functions such as malloc, scanf, printf, etc. are implemented in the simulator. Namely, to implement the builtin functions, you can simply write a C file like this one [https://github.com/Engineev/mocker/blob/master/builtin/builtin.c](url).
