### ISSUE TITLE
questions about / and %

### ISSUE THREAD

**Issue by jinhongyii** [peterzheng98/Compiler-2020#31]
in c ,-2 / 3 = 0, -2 % 3 = -2.
in python, -2 / 3 = -1, -2 % 3 = 1.
in mx, -2 / 3 = ? , -2 % 3 = ?
how to define / and % when it involves  negative numbers?

**Comment by Engineev** [comment]
The C convention.
Also, // (resp. /) in python3 (resp. python2) is floor division instead of integer division. See this [SO question](https://stackoverflow.com/questions/5535206/negative-integer-division-surprising-result).
