### ISSUE TITLE
Some error in misc-30.mx!

### ISSUE THREAD

**Issue by cla7aye15I4nd** [peterzheng98/Compiler-2020#35]
```c++
int getPrime(int N) {
    int count;
	int i;
    count = 2;
    for (i = 2; i <= N; i = i + 1) {
        if (b[i] == 1) {
            tmp[0] = tmp[0] + 1;
            prime[tmp[0]] = i;
            gps[i] = tmp[0];
        }
        while (i * count <= N) {
            b[i * count] = 0;
            count = count + 1;
        }
        count = 2;
    }
}
```
The getPrime function has no return statement, same error in printF in misc-30.

**Comment by Engineev** [comment]
Thank you for pointing out the mistakes. After some discussion, we decided,  to simplify the language, that the absence of `return` statement will no longer be viewed as a compilation error. Namely, all you need to do is to check whether the types are consistent when there exists a `return` statement. We will guarantee that in all codegen/optim test cases, if a function has an execution sequence that is not ended by a `return` statement, then that sequence will never be executed.
