### ISSUE TITLE
Questions about sema/class-14

### ISSUE THREAD

**Issue by wu-qing-157** [peterzheng98/Compiler-2020#36]
In class-14, we have the following code fragment:

``` C++
class b {
    int a;
    int b() { this.a = a }
};
```

And it is considered compilation fail due to "Constructor Type Error".
However, it is more likely to resolve this function as a member function, rather than a constructor, as there is 2 tokens (limited to primitive types and identifiers, and in this case, int and b) before the brackets, while constructors always have only one.
Therefore, this may not be a proper case to test "Constructor Type Error".
Besides that, there currently seems to be no more cases testing "Constructor Type Error", and the following case is not tested in any test case:

``` C++
class A {};
class B {
    A() {}
};
```

**Comment by xuyifangreeneyes** [comment]
We specify that the name of a member function cannot be the same as the (default) constructor name, so class-14 should fail.
