### ISSUE TITLE
Questions about global variable

### ISSUE THREAD

**Issue by wu-qing-157** [peterzheng98/Compiler-2020#40]
What's the behavior of the following global variable declarations? (CE, Correct or UB)

(initialize with const value)
```c++
int a = 123;
```
(initialize with const expression)
```c++
int a = 123 ^ 789;
```
(initialize with decidable value, but complicated)
```c++
int f(int a, int b) { return a ^ b; }
int a = f(123, 789);
```
(initialize with non-decidable value, a function must be called run-time)
```c++
int a = getInt();
```

**Comment by Engineev** [comment]
All of them are correct. Global initialization should happen before the entering of `main`, and the order of initialization is undefined.
